package by.epam.tc.web.controller.constant;

public final class CommandName{
	public final static String LOGINATION = "Logination";
	public final static String REGISTRATION = "Registration";
	public final static String EDIT_ACCOUNT = "Edit";
	public final static String EDIT_STAY = "EditStay";
	public final static String EDIT_STAY_CHECK = "EditStayCheck";
	public final static String ADD_CLIENT = "AddClient";
	public final static String ADD_BOOKING = "AddBooking";
	public final static String ADD_STAY = "AddStay";
	public final static String EDIT_BOOKING = "EditBooking";
	public final static String EDIT_BOOKING_CHECK = "EditBookingCheck";
	public final static String CHANGE_LANGUAGE = "ChangeLanguage";
	public final static String CHANGE_PASSWORD = "ChangePassword";
	public final static String SEARCH_ROOMS = "SearchRooms";
	public final static String BOOK_ROOM = "BookRoom";
	public final static String DELETE_ACCOUNT = "DeleteAccount";
	public final static String DELETE_BOOKING = "DeleteBooking";
	public final static String DELETE_STAY = "DeleteStay";
	public final static String CHECK_ROOM_AVAILABILITY = "CheckRoomAvailability";
	public final static String SUBMIT_BOOKING = "SubmitBooking";
	public final static String SUBMIT_CLIENT = "SubmitClient";
	public final static String CHOOSE_BOOKING = "ChooseBooking";
	public final static String APPROVE_BOOKING = "ApproveBooking";
	public final static String CHOOSE_STAY = "ChooseStay";
	public final static String SUBMIT_STAY = "SubmitStay";
	public final static String CHOOSE_CLIENT = "ChooseClient";	
	public final static String SEARCH_CLIENT = "SearchClient";
	public final static String FINISH_CHOOSING_CLIENT = "FinishChoosingClient";	
	public final static String GUESTS_ARRIVED = "GuestsArrived";
	public final static String GO_TO_WELCOME_PAGE = "GO_TO_WELCOME_PAGE";
	public final static String GO_TO_LOGINATION_PAGE = "GO_TO_LOGINATION_PAGE";	
	public final static String GO_TO_REGISTRATION_PAGE = "GO_TO_REGISTRATION_PAGE";	
	public final static String GO_TO_ROOMS_PAGE = "GO_TO_ROOMS_PAGE";
	public final static String GO_TO_ERROR_PAGE = "GO_TO_ERROR_PAGE";
	public final static String GO_TO_MY_ACCOUNT_PAGE = "GO_TO_MY_ACCOUNT_PAGE";
	public final static String GO_TO_BOOKINGS_PAGE = "GO_TO_BOOKINGS_PAGE";
	public final static String GO_TO_STAYS_PAGE = "GO_TO_STAYS_PAGE";
	public final static String GO_TO_CONTACTS_PAGE = "GO_TO_CONTACTS_PAGE";
	public final static String GO_TO_CLIENTS_PAGE = "GO_TO_CLIENTS_PAGE";
}