package by.epam.tc.web.controller.constant;

/** 
 * Class containing names of all parameters recognized by controller
 * 
 * @author Lizzi9223
 *
 */
public final class Utility {
	public final static String EMPTY = "";
	public final static String ID = "Id";
	public final static String CLIENTS = "clients";
	public final static String BOOKINGS = "bookings";
	public final static String STAYS = "stays";
	public final static String BOOKING = "booking";
	public final static String STAY = "stay";
	public final static String ROLE = "role";
	public final static String LOGIN = "login";
	public final static String PASSWORD = "password";
	public final static String INITIAL_PASSWORD = "initialPassword";
	public final static String NEW_PASSWORD = "newPassword";
	public final static String ADMIN = "admin";
	public final static String ADMINS = "admins";
	public final static String CLIENT = "client";
	public final static String CREATE = "create";
	public final static String MIN_COST = "minCost";
	public final static String MAX_COST = "maxCost";
	public final static String MIN_CAPACITY = "minCapacity";
	public final static String MAX_CAPACITY = "maxCapacity";
	public final static String CURRENT_MIN_COST = "currentMinCost";
	public final static String CURRENT_MAX_COST = "currentMaxCost";
	public final static String CURRENT_MIN_CAPACITY = "currentMinCapacity";
	public final static String CURRENT_MAX_CAPACITY = "currentMaxCapacity";
	public final static String PRICE_LEFT = "price-left";
	public final static String PRICE_RIGHT = "price-right";
	public final static String CAPACITY_LEFT = "capacity-left";
	public final static String CAPACITY_RIGHT = "capacity-right";
	public final static String SEARCH_GENDER = "searchGender";
	public final static String CURRENT_GENDER = "currentGender";
	public final static String SEARCH_BATHROOM = "searchBathroom";
	public final static String CURRENT_IS_BATHROOM = "currentIsBathroom";
	public final static String SELECTED_ROOMS = "selected_rooms";
	public final static String LOG_OUT = "logOut";
	public final static String REQUEST_ENCODING = "requestEncoding";
	public final static String ERROR = "error";
	public final static String BOOKING_ID = "bookingId";
	public final static String STAY_ID = "stayId";
	public final static String COMMAND = "command";
	public final static String POPUP_VIEW = "popUpView";
	public final static String FROM_DATE = "fromDate";
	public final static String TO_DATE = "toDate";
	public final static String GUESTS_NUMBER = "guestsNumber";
	public final static String ROOM_NUMBER = "roomNumber";
	public final static String NOTES = "notes";
	public final static String EDITED_NOTES = "editedNotes";
	public final static String EDITED_STAY_ID = "editedStayId";
	public final static String EDITED_BOOKING_ID = "editedBookingId";
	public final static String CHECK_RESULT = "checkResult";
	public final static String EDIT_BOOKING = "editBooking";
	public final static String NAME = "name";
	public final static String SURNAME = "surname";
	public final static String PASSPORT_ID = "passportId";
	public final static String DATE_OF_BIRTH = "dateOfBith";
	public final static String COUNTRY = "country";
	public final static String PHONE = "phone";
	public final static String EMAIL = "email";
	public final static String PHOTO = "photo";
	public final static String APPROVE = "approve";
	public final static String ROOM = "room";
	public final static String ROOM_TO_BOOK = "roomToBook";
	public final static String ALL_ROOMS = "allRooms";
	public final static String LANGUAGE = "language";
	public final static String URL = "url";
	public final static String CHECK_AMONG_ALL_ROOMS = "checkAmongAllRooms";
	public final static String AVAILABLE_ROOMS = "availableRooms";
	public final static String CHOSEN_BOOKING_ID = "chosenBookingId";
	public final static String CHOSEN_BOOKING_IS_APPROVED = "chosenBookingIsApproved";
	public final static String CHOSEN_BOOKING_IS_PAID = "chosenBookingIsPaid";
	public final static String CHOSEN_STAY_ID = "chosenStayId";
	public final static String OPTIONS = "options";
	public final static String NEW_STAY_FROM_DATE = "newStayFromDate";
	public final static String NEW_STAY_TO_DATE = "newStayToDate";
	public final static String NEW_STAY_ROOM_NUMBER = "newStayRoomNumber";
	public final static String NEW_STAY_GUESTS_NUMBER = "newStayGuestsNumber";
	public final static String NEW_STAY_GUESTS_TO_ADD = "newStayGuestsToAdd";
	public final static String GUESTS_ARRIVED_BOOKING_ID = "guestsArrivedBookingId";
	public final static String CHOSEN_CLIENT = "chosenClient";
	public final static String CHOSEN_CLIENT_ID = "chosenClientId";
	public final static String CHOSEN_ADMIN = "chosenAdmin";
	public final static String CHOSEN_ADMIN_ID = "chosenAdminId";
	public final static String CLIENT_IS_ALREADY_ADDED = "clientIsAlreadyAdded";
	public final static String ALL_CLIENT_USERS = "allClientUsers";
	public final static String SEARCH_CRITERIA = "searchCriteria";
	public final static String SEARCH_DATA = "searchData";
	public final static String EDITED_CLIENT_ID = "editedClientId";
	public final static String CURRENT_SEARCH_CRITERIA = "currentSearchCriteria";
	public final static String CURRENT_SEARCH_DATA = "currentSearchData";
	public final static String BLACKLIST_CLIENTS = "blacklistClients";
	public final static String REGULAR_CLIENTS = "regularClients";
	public final static String SINCE_DATE = "sinceDate";
	public final static String REASON = "reason";
	public final static String DISCOUNT = "discount";
}